// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AzureOpenAIChat.Models;

public partial class Article
{
    public int Id { get; set; }

    public string ArticleName { get; set; }

    public virtual ICollection<ArticleDetail> ArticleDetail { get; set; } = new List<ArticleDetail>();
}