// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AzureOpenAIChat.Models;

public partial class ArticleDetail
{
    public int Id { get; set; }

    public int ArticleId { get; set; }

    public int ArticleSequence { get; set; }

    public string ArticleContent { get; set; }

    public virtual Article Article { get; set; }

    public virtual ICollection<ArticleVectorData> ArticleVectorData { get; set; } = new List<ArticleVectorData>();
}