// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AzureOpenAIChat.Models
{
    public partial class SimilarContentArticlesResult
    {
        public string ArticleName { get; set; }
        public string ArticleContent { get; set; }
        public int ArticleSequence { get; set; }
        public double? cosine_distance { get; set; }
    }
}
